---@diagnostic disable

animlist = {
  { dict = "rcmpaparazzo_2",                                              anim = "shag_loop_a",                        name = "NSFW: Hit It From The Back 01",         flag = 47, type = 7,                         boneID = 0,                             pedType = "PED_TYPE_PROSTITUTE", pedHash = 1846523796, posx = 0.0,     posy = 0.2,           posz = 0.0,            rotx = 40.0,     roty = 0.0,                     rotz = 0.0,                              dict2 = "rcmpaparazzo_2",       anim2 = "shag_loop_poppy", sfx = "SEX_GENERIC_FEM",        sfxName = "S_F_Y_HOOKER_03_BLACK_FULL_01", sfxFlg = "SPEECH_PARAMS_FORCE" },
  { dict = "misscarsteal2pimpsex",                                        anim = "shagloop_pimp",                      name = "NSFW: Hit It From The Front",           flag = 47, type = 7,                         boneID = 0,                             pedType = "PED_TYPE_PROSTITUTE", pedHash = 1846523796, posx = 0.05,    posy = 0.3,           posz = -0.2,           rotx = 27.0,     roty = 0.0,                     rotz = 190.0,                            dict2 = "misscarsteal2pimpsex", anim2 = "shagloop_hooker", sfx = "SEX_GENERIC_FEM",        sfxName = "S_F_Y_HOOKER_03_BLACK_FULL_01", sfxFlg = "SPEECH_PARAMS_FORCE" },

  { dict = "anim@scripted@ulp_missions@injured_agent@",                   anim = "idle_male",                          name = "Movement: Injured On The Ground",       flag = 47, ptfxdict = "core",                ptfxname = "ped_blood_drips",           ptfxdelay = 100,                 ptfxscale = 10,       ptfxOffx = 0.0, ptfxOffy = 0.0,       ptfxOffz = 0.0,        ptfxrotx = 0.0,  ptfxroty = 0.0,                 ptfxrotz = 0.0,                          type = 2 },
  { dict = "combat@damage@writheidle_a",                                  anim = "writhe_idle_a",                      name = "Movement: Injured On The Ground 2",     flag = 47, ptfxdict = "core",                ptfxname = "ped_blood_drips",           ptfxdelay = 100,                 ptfxscale = 1.0,      ptfxOffx = 0.0, ptfxOffy = 0.0,       ptfxOffz = 0.0,        ptfxrotx = 0.0,  ptfxroty = 0.0,                 ptfxrotz = 0.0,                          type = 2 },
  { dict = "missbigscore1switch_trevor_piss",                             anim = "piss_loop",                          name = "Action: Take A Piss",                   flag = 49, ptfxdict = "scr_amb_chop",        ptfxname = "ent_anim_dog_peeing",       ptfxdelay = 300,                 ptfxscale = 1.0,      ptfxOffx = 0.0, ptfxOffy = 0.1369101, ptfxOffz = 0.0,        ptfxrotx = 0.0,  ptfxroty = 40.0,                ptfxrotz = 90.0,                         type = 2 },
  { dict = "switch@trevor@on_toilet",                                     anim = "trev_on_toilet_loop",                name = "Action: Take A Shit",                   flag = 47, ptfxdict = "scr_amb_chop",        ptfxname = "ent_anim_dog_poo",          ptfxdelay = 500,                 ptfxscale = 1.0,      ptfxOffx = 0.2, ptfxOffy = -0.15,     ptfxOffz = -0.1,       ptfxrotx = 0.0,  ptfxroty = 0.0,                 ptfxrotz = 0.0,                          type = 2 },
  { dict = "ragdoll@human",                                               anim = "electrocute",                        name = "Movement: Ragdoll (tased)",             flag = 02, ptfxdict = "veh_xs_vehicle_mods", ptfxname = "veh_xs_electrified_rambar", ptfxdelay = 30,                  ptfxscale = 0.42069,  ptfxOffx = 0.0, ptfxOffy = -1.5,      ptfxOffz = 0.0,        ptfxrotx = 0.0,  ptfxroty = 0.0,                 ptfxrotz = 0.0,                          type = 2,                       sfx = "PAIN_TAZER",        sfxName = "WAVELOAD_PAIN_MALE", sfxFlg = "SPEECH_PARAMS_FORCE" },
  { dict = "ragdoll@human",                                               anim = "on_fire",                            name = "Movement: Ragdoll (on fire)",           flag = 02, ptfxdict = "core",                ptfxname = "fire_wrecked_tank",         ptfxdelay = 69,                  ptfxscale = 0.69420,  ptfxOffx = 0.0, ptfxOffy = 0.0,       ptfxOffz = -0.0069420, ptfxrotx = 0.0,  ptfxroty = 0.0,                 ptfxrotz = 0.0,                          type = 2,                       sfx = "ON_FIRE",           sfxName = "WAVELOAD_PAIN_MALE", sfxFlg = "SPEECH_PARAMS_FORCE" },

  { dict = "missheistdockssetup1clipboard@base",                          anim = "base",                               name = "MISC: Clipboard",                       flag = 49, prop1 = 2896824542,               boneID = 60309,                         posx = 0.011,                    posy = 0.007,         posz = -0.02,   rotx = 96.2,          roty = 0.0,            rotz = 0.0,      prop2 = 463086472,              bone2 = 58867,                           posx2 = 0.05,                   posy2 = -0.01,             posz2 = -0.01,                  rotx2 = 0.0,                               roty2 = 0.0,                   rotz2 = 0.0,     type = 6 },

  { dict = "amb@world_human_drinking@beer@male@idle_a",                   anim = "idle_a",                             name = "MISC: Drink Beer 01",                   flag = 49, prop1 = 2010247122,               boneID = 28422,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@world_human_drinking@beer@female@idle_a",                 anim = "idle_b",                             name = "MISC: Drink Beer 02",                   flag = 49, prop1 = 2010247122,               boneID = 28422,                         posx = -0.02,                    posy = 0.0,           posz = 0.0,     rotx = 10.0,          roty = 10.0,           rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@world_human_drinking@coffee@male@idle_a",                 anim = "idle_c",                             name = "MISC: Drink Coffee 01",                 flag = 49, prop1 = 4161278897,               boneID = 64096,                         posx = 0.01,                     posy = 0.055,         posz = -0.005,  rotx = -15.0,         roty = 5.0,            rotz = -87.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@world_human_drinking@coffee@female@idle_a",               anim = "idle_b",                             name = "MISC: Drink Coffee 02",                 flag = 49, prop1 = 4161278897,               boneID = 64096,                         posx = 0.015,                    posy = 0.066,         posz = -0.011,  rotx = -15.0,         roty = 5.0,            rotz = -120.0,   ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@code_human_wander_eating_donut@male@base",                anim = "static",                             name = "MISC: Eat Donut",                       flag = 49, prop1 = 3992024553,               boneID = 64096,                         posx = 0.06,                     posy = 0.05,          posz = 0.02,    rotx = -90.0,         roty = 180.0,          rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@world_human_seat_wall_eating@male@both_hands@idle_a",     anim = "idle_c",                             name = "MISC: Eat Taco",                        flag = 49, prop1 = 1655278098,               boneID = 64096,                         posx = 0.1,                      posy = 0.05,          posz = 0.01,    rotx = -25.0,         roty = 0.0,            rotz = 290.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@world_human_musician@guitar@male@idle_a",                 anim = "idle_b",                             name = "Activity: Guitar (acoustic)",           flag = 33, prop1 = 3586178055,               boneID = 24818,                         posx = -0.06,                    posy = 0.29,          posz = 0.18,    rotx = 10.0,          roty = 348.0,          rotz = 161.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@world_human_musician@guitar@male@idle_a",                 anim = "idle_a",                             name = "Activity: Guitar (electric)",           flag = 33, prop1 = 61087258,                 boneID = 24818,                         posx = -0.01,                    posy = 0.27,          posz = 0.18,    rotx = 14.0,          roty = 348.0,          rotz = 161.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Pizza Box",                 flag = 49, prop1 = 3438383125,               boneID = 28422,                         posx = 0.01,                     posy = -0.1,          posz = -0.159,  rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Money Suitcase",            flag = 49, prop1 = 1452661060,               boneID = 28422,                         posx = 0.0,                      posy = -0.35,         posz = -0.12,   rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry T-Shirt Box",               flag = 49, prop1 = 296207441,                boneID = 28422,                         posx = -0.01,                    posy = -0.3,          posz = -0.180,  rotx = 0.0,           roty = 0.0,            rotz = 90.0,     ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Beer Box",                  flag = 49, prop1 = 1661171057,               boneID = 28422,                         posx = -0.01,                    posy = -0.1,          posz = -0.02,   rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Weed Plant",                flag = 49, prop1 = 3366029953,               boneID = 28422,                         posx = -0.005,                   posy = -0.12,         posz = -0.18,   rotx = 20.0,          roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Weed Package",              flag = 49, prop1 = 1009806427,               boneID = 28422,                         posx = -0.02,                    posy = -0.28,         posz = -0.2,    rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Cocaine Package",           flag = 49, prop1 = 1188944846,               boneID = 28422,                         posx = 0.0,                      posy = -0.2,          posz = -0.05,   rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Meth Package",              flag = 49, prop1 = 125438837,                boneID = 28422,                         posx = 0.0,                      posy = -0.3,          posz = -0.18,   rotx = 0.0,           roty = 0.0,            rotz = 90.0,     ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Dead Body 01",              flag = 49, prop1 = 462487855,                boneID = 28422,                         posx = -0.15,                    posy = -0.15,         posz = -0.2,    rotx = -20.0,         roty = -30.0,          rotz = 180.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@box_carry@",                                      anim = "idle",                               name = "MISC: Carry Dead Body 02",              flag = 49, prop1 = 2416598663,               boneID = 28422,                         posx = 0.15,                     posy = -0.05,         posz = -0.2,    rotx = 20.0,          roty = 35.0,           rotz = 180.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@narcotics@trash",                                 anim = "idle",                               name = "MISC: Carry Trash",                     flag = 49, prop1 = 3619689535,               boneID = 28422,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "anim@heists@narcotics@trash",                                 anim = "idle",                               name = "MISC: Carry Katana",                    flag = 49, prop1 = 3803840879,               boneID = 28422,                         posx = 0.0,                      posy = -0.03,         posz = 0.02,    rotx = -60.0,         roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@prop_human_bum_shopping_cart@male@idle_a",                anim = "idle_c",                             name = "HOBO Trolley",                          flag = 33, prop1 = 4064921930,               boneID = 0,                             posx = 0.0,                      posy = 1.05,          posz = -0.5,    rotx = 0.0,           roty = 0.0,            rotz = 180.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 3,                      propColl = true, prop2 = 0 },
  { dict = "amb@world_human_bum_freeway@male@idle_a",                     anim = "idle_a",                             name = "HOBO Begging",                          flag = 49, prop1 = 4049581021,               boneID = 28422,                         posx = 0.0,                      posy = 0.0,           posz = 0.08,    rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "missfbi1",                                                    anim = "ledge_loop",                         name = "MISC: Naruto Run (probably. idk)",      flag = 49, prop1 = 3760607069,               boneID = 12844,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 90.0,           rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@code_human_in_car_mp_actions@grab_crotch@low@ds@base",    anim = "idle_a",                             name = "NSFW: Smells So Good!",                 flag = 49, prop1 = 2881667978,               boneID = 12844,                         posx = 0.12,                     posy = 0.0,           posz = 0.003,   rotx = 90.0,          roty = 90.0,           rotz = 180.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "timetable@ron@ig_3_couch",                                    anim = "base",                               name = "MISC: Sit On Chair 01",                 flag = 34, prop1 = 3186063286,               boneID = 23553,                         posx = -0.21,                    posy = 0.0,           posz = 0.0,     rotx = 185.0,         roty = 86.0,           rotz = -20.0,    ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "random@crash_rescue@get_victim_to_friend",                    anim = "helping_friend_idle_friend",         name = "MISC: Sit On Chair 02",                 flag = 34, prop1 = 1103738692,               boneID = 23553,                         posx = 0.03,                     posy = -0.03,         posz = 0.0,     rotx = 185.0,         roty = 92.1069420,     rotz = 50.0,     ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "timetable@ron@ig_5_p3",                                       anim = "ig_5_p3_base",                       name = "MISC: Sit On Chair 03",                 flag = 33, prop1 = 2278414290,               boneID = 23553,                         posx = -0.46,                    posy = -0.46,         posz = -0.1,    rotx = 180.0,         roty = 96.0,           rotz = 35.0,     ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "timetable@reunited@ig_10",                                    anim = "base_amanda",                        name = "MISC: Sit On Chair 04",                 flag = 33, prop1 = 725259233,                boneID = 23553,                         posx = -0.46,                    posy = -0.46,         posz = 0.05,    rotx = 180.0,         roty = 85.0,           rotz = 35.0,     ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "switch@michael@sunlounger",                                   anim = "sunlounger_idle",                    name = "MISC: Relax On Lounger",                flag = 34, prop1 = 3721259803,               boneID = 23553,                         posx = 0.09,                     posy = -0.595555,     posz = 0.0,     rotx = 178.0,         roty = 91.0,           rotz = 60.0,     ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 1,                      propColl = true, prop2 = 0 },
  { dict = "amb@world_human_picnic@female@base",                          anim = "base",                               name = "MISC: Sit On Ground (female)",          flag = 47, prop1 = 951345131,                boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxOffx = 0.0,                 ptfxOffy = 0.0,                          ptfxOffz = 0.0,                 ptfxrotx = 0.0,            ptfxroty = 0.0,                 ptfxrotz = 0.0,                            type = 3,                      propColl = true, prop2 = 0 },

  { dict = "dead",                                                        anim = "dead_e",                             name = "Action: Dead 01",                       flag = 02, prop1 = 0,                        boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ent_sht_blood",              ptfxdelay = 400,                ptfxscale = 0.2,           ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 2, propColl = true, prop2 = 0 },
  { dict = "dead",                                                        anim = "dead_f",                             name = "Action: Dead 02",                       flag = 02, prop1 = 0,                        boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ent_sht_blood",              ptfxdelay = 400,                ptfxscale = 0.2,           ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 2, propColl = true, prop2 = 0 },
  { dict = "dead",                                                        anim = "dead_d",                             name = "Action: Dead 03",                       flag = 02, prop1 = 0,                        boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ent_sht_blood",              ptfxdelay = 400,                ptfxscale = 0.2,           ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 2, propColl = true, prop2 = 0 },
  { dict = "amb@world_human_paparazzi@male@base",                         anim = "base",                               name = "MISC: Photograph",                      flag = 49, prop1 = 680380202,                boneID = 28422,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "scr_bike_business", ptfxname = "scr_bike_cfid_camera_flash", ptfxdelay = 1000,               ptfxscale = 0,             ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 5, propColl = true, prop2 = 0 },
  { dict = "oddjobs@taxi@gyn@cc@hotbox",                                  anim = "idle_b",                             name = "Car: Smoke Cigarette (in-car)",         flag = 33, prop1 = 3269700402,               boneID = 28422,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ent_anim_cig_smoke",         ptfxdelay = 0,                  ptfxscale = 1,             ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 5, propColl = true, prop2 = 0 },
  { dict = "amb@world_human_aa_smoke@male@idle_a",                        anim = "idle_a",                             name = "MISC: Smoke Cigarette 01",              flag = 49, prop1 = 3269700402,               boneID = 28422,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ent_anim_cig_smoke",         ptfxdelay = 0,                  ptfxscale = 1,             ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 5, propColl = true, prop2 = 0 },
  { dict = "amb@world_human_leaning@female@wall@back@hand_up@base",       anim = "base",                               name = "MISC: Smoke Cigarette 02",              flag = 33, prop1 = 3269700402,               boneID = 64096,                         posx = 0.0,                      posy = 0.0,           posz = -0.01,   rotx = 0.0,           roty = 0.0,            rotz = 60.0,     ptfxdict = "core",              ptfxname = "ent_anim_cig_smoke",         ptfxdelay = 0,                  ptfxscale = 1,             ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 5, propColl = true, prop2 = 0 },
  { dict = "amb@world_human_aa_smoke@male@idle_a",                        anim = "idle_a",                             name = "MISC: Smoke Cigar",                     flag = 49, prop1 = 3909405573,               boneID = 64096,                         posx = 0.02069,                  posy = -0.01,         posz = -0.02,   rotx = 50.0,          roty = 0.0,            rotz = -80.0,    ptfxdict = "core",              ptfxname = "ent_anim_cig_smoke",         ptfxdelay = 0,                  ptfxscale = 1,             ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 5, propColl = true, prop2 = 0 },
  { dict = "amb@world_human_smoking_pot@male@base",                       anim = "base",                               name = "MISC: Smoke Weed",                      flag = 49, prop1 = 2664795270,               boneID = 60309,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 55,            roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ent_anim_weed_smoke",        ptfxdelay = 0,                  ptfxscale = 1,             ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 5, propColl = true, prop2 = 0 },
  { dict = "anim@gangops@hostage@",                                       anim = "victim_fail",                        name = "Movement: Ragdoll (shot in the head)",  flag = 02, prop1 = 0,                        boneID = 12844,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ent_sht_blood",              ptfxdelay = 200,                ptfxscale = 0.5,           ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 2 },
  { dict = "switch@michael@wash_face",                                    anim = "loop_michael",                       name = "Action: Wash Face",                     flag = 33, prop1 = 0,                        boneID = 12844,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "water_splash_ped_wade",      ptfxdelay = 200,                ptfxscale = 0.5,           ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 2 },
  { dict = "anim@scripted@nightclub@vomit@",                              anim = "vomit",                              name = "Action: Vomit",                         flag = 49, prop1 = 0,                        boneID = 12844,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "scr_family5",       ptfxname = "scr_trev_puke",              ptfxdelay = 200,                ptfxscale = 0.5,           ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 2 },
  { dict = "mp_suicide",                                                  anim = "pistol",                             name = "Action: Commit Seppuku (×_×) (pistol)", flag = 02, prop1 = 0,                        boneID = 12844,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ent_sht_blood",              ptfxdelay = 800,                ptfxscale = 1.0,           ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 2 },
  { dict = "move_injured_ground",                                         anim = "sider_loop",                         name = "Movement: Crawl Forward (injured)",     flag = 33, prop1 = 0,                        boneID = 12844,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      ptfxdict = "core",              ptfxname = "ped_blood_drips",            ptfxdelay = 30,                 ptfxscale = 1.0,           ptfxOffx = 0.0,                 ptfxOffy = 0.0,                            ptfxOffz = 0.0,                ptfxrotx = 0.0,  ptfxroty = 0.0, ptfxrotz = 0.0, type = 2 },

  { dict = "missmic2@meat_hook",                                          anim = "michael_meat_hook_react_c",          name = "Action: Hang Upside-Down",              flag = 33, prop1 = 3005341058,               boneID = 65245,                         posx = -0.018,                   posy = 0.1,           posz = 0.15,    rotx = -30.0,         roty = 0.0,            rotz = 0.0,      type = 1 },
  { dict = "amb@world_human_hiker_standing@male@base",                    anim = "base",                               name = "Movement: Hiker",                       flag = 49, prop1 = 2157846744,               boneID = 24818,                         posx = -0.05,                    posy = -0.2,          posz = 0.0,     rotx = 0.0,           roty = 90.0,           rotz = -20.0,    type = 1 },
  { dict = "anim@scripted@ulp_missions@computerhack@heeled@",             anim = "hacking_loop",                       name = "MISC: Hacker",                          flag = 33, prop1 = 3940780948,               boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 3 },
  { dict = "rcmjosh2",                                                    anim = "josh_2_intp1_base",                  name = "MISC: Ghost Girlfriend",                flag = 49, prop1 = 3270826173,               boneID = 60309,                         posx = 1.4,                      posy = 0.0,           posz = 0.12,    rotx = 90.0,          roty = -5.0,           rotz = -90.0,    type = 1 },
  { dict = "rcmjosh2",                                                    anim = "josh_2_intp1_base",                  name = "MISC: Ghost Boyfriend",                 flag = 49, prop1 = 2932993356,               boneID = 60309,                         posx = 1.5,                      posy = 0.0,           posz = 0.15,    rotx = 90.0,          roty = -5.0,           rotz = -90.0,    type = 1 },
  { dict = "amb@medic@standing@kneel@idle_a",                             anim = "idle_b",                             name = "Action: Crime Scene Medic",             flag = 1,  tprop1 = 3026386862,              boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = -0.0,           rotz = 20.0,     type = 3 },
  { dict = "amb@code_human_police_investigate@idle_a",                    anim = "idle_a",                             name = "Action: Crime Scene Investigator",      flag = 1,  tprop1 = 3026386862,              boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 20.0,     type = 3 },
  { dict = "amb@world_human_clipboard@male@base",                         anim = "base",                               name = "NSFW: Porn Magazine 01",                flag = 49, prop1 = 2727617608,               boneID = 60309,                         posx = 0.08,                     posy = -0.049,        posz = -0.05,   rotx = 87.93,         roty = -0.4292,        rotz = -14.3925, type = 1 },
  { dict = "amb@world_human_clipboard@male@base",                         anim = "base",                               name = "NSFW: Porn Magazine 02",                flag = 49, prop1 = 3306343310,               boneID = 60309,                         posx = 0.12,                     posy = -0.049,        posz = -0.05,   rotx = 87.93,         roty = -0.4292,        rotz = -14.3925, type = 1 },
  { dict = "amb@incar@male@patrol@torch@idle_a",                          anim = "idle_a",                             name = "Car: Police Torch Right (in-car)",      flag = 33, prop1 = 211760048,                boneID = 28422,                         posx = 0.0,                      posy = -0.009,        posz = -0.01,   rotx = 0.0,           roty = 0.0,            rotz = 90.0,     type = 1 },
  { dict = "amb@incar@male@patrol@torch@idle_b",                          anim = "idle_d",                             name = "Car: Police Torch Left (in-car)",       flag = 33, prop1 = 211760048,                boneID = 28422,                         posx = 0.0,                      posy = -0.009,        posz = -0.01,   rotx = 0.0,           roty = 0.0,            rotz = 90.0,     type = 1 },
  { dict = "amb@world_human_sunbathe@male@back@base",                     anim = "base",                               name = "MISC: Sunbathe",                        flag = 33, prop1 = 1280564504,               boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 4,                       propColl = true },
  { dict = "timetable@tracy@sleep@",                                      anim = "idle_b",                             name = "MISC: Sleep",                           flag = 33, prop1 = 3314781611,               boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 4,                       propColl = true,                         sfx = "SNORING",                sfxName = "TREVOR_NORMAL", sfxFlg = "SPEECH_PARAMS_FORCE" },
  { dict = "anim@amb@nightclub@lazlow@hi_dancefloor@",                    anim = "crowddance_hi_11_raiseup_laz",       name = "Activity: Dance 01",                    flag = 33, prop1 = 3324004640,               boneID = 64096,                         posx = 0.02481,                  posy = 0.05,          posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 1,                       propColl = true },
  { dict = "anim@amb@nightclub@dancers@solomun_entourage@",               anim = "mi_dance_prop_15_v1_male^1",         name = "Activity: Dance 06",                    flag = 33, prop1 = 1940235411,               boneID = 64096,                         posx = 0.015,                    posy = 0.04,          posz = -0.12,   rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 1,                       propColl = true },
  { dict = "anim@amb@nightclub@djs@solomun@",                             anim = "sol_sync_b_sol",                     name = "Activity: DJ 01 (Solomun)",             flag = 47, prop1 = 2767137151,               boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 3,                       propColl = true },
  { dict = "anim@amb@nightclub@djs@dixon@",                               anim = "dixn_sync_cntr_g_dix",               name = "Activity: DJ 02 (Dixon)",               flag = 47, prop1 = 2767137151,               boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 3,                       propColl = true },
  { dict = "anim@amb@nightclub@djs@black_madonna@",                       anim = "pose_a_idle_e_blamadon",             name = "Activity: DJ 03 (Black Madonna)",       flag = 47, prop1 = 2767137151,               boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 3,                       propColl = true },
  { dict = "mini@strip_club@idles@dj@idle_02",                            anim = "idle_02",                            name = "Activity: DJ 04",                       flag = 47, prop1 = 976772591,                boneID = 0,                             posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 3,                       propColl = true },
  { dict = "amb@world_human_stand_fishing@idle_a",                        anim = "idle_a",                             name = "Activity: Fishing",                     flag = 49, prop1 = 2384362703,               boneID = 36029,                         posx = 0.1,                      posy = 0.08,          posz = 0.03,    rotx = 0,             roty = 267,            rotz = 230,      type = 1,                       propColl = true },
  { dict = "amb@world_human_stand_mobile@male@text@base",                 anim = "base",                               name = "MISC: Browse Phone",                    flag = 49, prop1 = 3083764787,               boneID = 28422,                         posx = 0.0,                      posy = 0.0,           posz = 0.0,     rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 1,                       propColl = true },
  { dict = "switch@trevor@jerking_off",                                   anim = "trev_jerking_off_loop",              name = "NSFW: Jerk off",                        flag = 49, prop1 = 3872089630,               boneID = 64096,                         posx = 0.0053,                   posy = 0.02,          posz = 0.01,    rotx = 0.0,           roty = 0.0,            rotz = 0.0,      type = 1,                       propColl = true },
  { dict = "mini@strip_club@private_dance@part3",                         anim = "priv_dance_p3",                      name = "NSFW: Lap Dance 02",                    flag = 47, prop1 = 3246457862,               boneID = 12844,                         posx = -0.01,                    posy = 0.115,         posz = -0.1,    rotx = 0.0,           roty = 0.0,            rotz = 90.0,     type = 1,                       propColl = true },
  { dict = "timetable@trevor@skull_loving_bear",                          anim = "skull_loving_bear",                  name = "NSFW: Hit It From The Back 02",         flag = 47, prop1 = 1022578470,               boneID = 64096,                         posx = -0.069420,                posy = -0.1,          posz = -0.1,    rotx = 32.0,          roty = 50.0,           rotz = 40.0,     type = 1,                       propColl = true },
  { dict = "misscarsteal2fixer",                                          anim = "confused_a",                         name = "Car: Mechanic 01",                      flag = 33, prop1 = 1996755764,               boneID = 6286,                          posx = 0.05,                     posy = 0.01,          posz = -0.02,   rotx = 100.0,         roty = -30.0,          rotz = 0.0,      type = 1,                       propColl = true },
  { dict = "timetable@jimmy@mics3_ig_15@",                                anim = "idle_a_jimmy",                       name = "MISC: Sit On Ground (knee up)",         flag = 47 },
  { dict = "anim@amb@business@bgen@bgen_no_work@",                        anim = "sit_phone_phoneputdown_idle_nowork", name = "MISC: Sit On Ground (both knees up)",   flag = 47 },
  { dict = "amb@world_human_leaning@female@wall@back@holding_elbow@base", anim = "base",                               name = "MISC: Lean Back Hold Elbow",            flag = 33 },
  { dict = "amb@world_human_leaning@male@wall@back@foot_up@aggro_react",  anim = "aggro_react_forward_exit",           name = "MISC: Lean Back Foot Up",               flag = 34 },
  { dict = "anim@amb@nightclub@gt_idle@",                                 anim = "base",                               name = "MISC: Lean Back On Rail/Ledge",         flag = 34 },
  { dict = "switch@michael@sitting_on_car_bonnet",                        anim = "sitting_on_car_bonnet_loop",         name = "Car: Sit On Car Hood",                  flag = 33 },
  { dict = "timetable@mime@01_gc",                                        anim = "idle_a",                             name = "MISC: Lean On Elbow Left",              flag = 33 },
  { dict = "misscarstealfinale",                                          anim = "packer_idle_1_trevor",               name = "MISC: Lean On Hand Left",               flag = 33 },
  { dict = "anim@amb@garage@chassis_repair@",                             anim = "idle_02_amy_skater_01",              name = "Car: Mechanic 02",                      flag = 33 },
  { dict = "missarmenian2",                                               anim = "standing_idle_loop_drunk",           name = "Movement: Drunk (static)",              flag = 33 },
  { dict = "random@drunk_driver_1",                                       anim = "drunk_driver_stand_loop_dd2",        name = "Movement: Drunk",                       flag = 49 },
  { dict = "anim@amb@nightclub@mini@dance@dance_solo@sand_trip@",         anim = "high_left_up",                       name = "Activity: Dance 02",                    flag = 33 },
  { dict = "anim@amb@nightclub@dancers@dixon_entourage@",                 anim = "mi_dance_facedj_15_v1_male^4",       name = "Activity: Dance 03",                    flag = 33 },
  { dict = "anim@move_f@grooving@",                                       anim = "walk",                               name = "Movement: Goofy Walk",                  flag = 49 },
  { dict = "move_m@joy@a",                                                anim = "walk",                               name = "Movement: Boss Walk",                   flag = 49 },
  { dict = "rcmepsilonism8",                                              anim = "worship_base",                       name = "Action: Speaketh To Thy Lord",          flag = 49 },
  { dict = "amb@world_human_jog_standing@female@idle_a",                  anim = "idle_a",                             name = "Movement: Goofy Run",                   flag = 49 },
  { dict = "switch@franklin@press_ups",                                   anim = "pressups_loop",                      name = "Activity: Push-ups",                    flag = 47 },
  { dict = "amb@world_human_sit_ups@male@base",                           anim = "base",                               name = "Activity: Sit-ups",                     flag = 47 },
  { dict = "anim@mp_player_intincarrockstd@ps@",                          anim = "idle_a",                             name = "Gesture: Metal",                        flag = 47 },
  { dict = "mini@strip_club@private_dance@part2",                         anim = "priv_dance_p2",                      name = "NSFW: Lap Dance 01",                    flag = 47 },
  { dict = "switch@trevor@mocks_lapdance",                                anim = "001443_01_trvs_28_idle_stripper",    name = "NSFW: Twerk",                           flag = 47 },
  { dict = "mini@prostitutes@sexlow_veh",                                 anim = "low_car_sex_loop_female",            name = "NSFW: Ride Dick In Car",                flag = 47 },
  { dict = "anim@mini@prostitutes@sex@veh_vstr@",                         anim = "bj_loop_prostitute",                 name = "NSFW: Give Head In Car",                flag = 47 },
  { dict = "anim@mini@prostitutes@sex@veh_vstr@",                         anim = "bj_loop_male",                       name = "NSFW: Receive Head In Car",             flag = 47 },
  { dict = "misscarsteal2pimpsex",                                        anim = "pimpsex_hooker",                     name = "NSFW: Give Head",                       flag = 47 },
  { dict = "misscarsteal2pimpsex",                                        anim = "shagloop_hooker",                    name = "NSFW: Take It From The Front",          flag = 47 },
  { dict = "rcmpaparazzo_2",                                              anim = "shag_loop_poppy",                    name = "NSFW: Take It From The Back",           flag = 47 },
  { dict = "mp_player_int_uppergrab_crotch",                              anim = "mp_player_int_grab_crotch",          name = "Action: Hold Your Nutts",               flag = 49 },
  { dict = "mp_player_int_upperarse_pick",                                anim = "mp_player_int_arse_pick",            name = "Action: Scratch Your Ass",              flag = 49 },
  { dict = "missminuteman_1ig_2",                                         anim = "handsup_base",                       name = "Action: Hands Up",                      flag = 49 },
  { dict = "mp_missheist_countrybank@lift_hands",                         anim = "lift_hands_in_air_outro",            name = "Action: Hands Up (static)",             flag = 50 },
  { dict = "nm@hands",                                                    anim = "flail",                              name = "Action: T-Pose",                        flag = 50 },
  { dict = "mp_defend_base",                                              anim = "guard_handsup_loop",                 name = "Action: Hands Up Scared",               flag = 49 },
  { dict = "missheist_agency2ahands_up",                                  anim = "handsup_anxious",                    name = "Action: Hands Up Scared 2",             flag = 49 },
  { dict = "anim@mp_player_intupperjazz_hands",                           anim = "idle_a",                             name = "Action: Jazz Hands",                    flag = 49 },
  { dict = "random@arrests@busted",                                       anim = "idle_a",                             name = "Action: Surrender 01",                  flag = 49 },
  { dict = "random@arrests@busted",                                       anim = "idle_a",                             name = "Action: Surrender 02 (on your knees)",  flag = 47 },
  { dict = "veh@busted_bike@sport@",                                      anim = "stay_in_car_crim",                   name = "Action: Surrender (sports bike)",       flag = 34 },
  { dict = "veh@busted_bike@chopper@",                                    anim = "busted",                             name = "Action: Surrender (chopper bike)",      flag = 34 },
  { dict = "veh@busted_std",                                              anim = "stay_in_car_crim",                   name = "Action: Surrender (regular car)",       flag = 34 },
  { dict = "veh@busted_low",                                              anim = "stay_in_car_crim",                   name = "Action: Surrender (sports car)",        flag = 34 },
  { dict = "veh@busted_truck",                                            anim = "stay_in_car_crim",                   name = "Action: Surrender (truck)",             flag = 34 },
  { dict = "veh@busted_van",                                              anim = "stay_in_car_crim",                   name = "Action: Surrender (van)",               flag = 34 },
  { dict = "misscarsteal4@toilet",                                        anim = "desperate_toilet_base_idle",         name = "MISC: HAS TO PEE!",                     flag = 47 },
  { dict = "timetable@jimmy@doorknock@",                                  anim = "knockdoor_idle",                     name = "Action: Knock On Door",                 flag = 51 },
  { dict = "move_m@_idles@shake_off",                                     anim = "shakeoff_1",                         name = "Action: Shake Dirt Off Clothes",        flag = 48 },
  { dict = "rcmnigel1c",                                                  anim = "hailing_whistle_waive_a",            name = "Gesture: Whistle",                      flag = 48 },
  { dict = "friends@frj@ig_1",                                            anim = "wave_a",                             name = "Gesture: Wave",                         flag = 48 },
  { dict = "random@car_thief@victimpoints_ig_3",                          anim = "arms_waving",                        name = "Gesture: Wave (both hands)",            flag = 48 },
  { dict = "gestures@m@standing@casual",                                  anim = "gesture_hello",                      name = "Gesture: Wave (subtle)",                flag = 48 },
  { dict = "mp_ped_interaction",                                          anim = "handshake_guy_b",                    name = "Gesture: Handshake 01",                 flag = 48 },
  { dict = "mp_ped_interaction",                                          anim = "handshake_guy_a",                    name = "Gesture: Handshake 02",                 flag = 48 },
  { dict = "anim@mp_player_intselfieblow_kiss",                           anim = "exit",                               name = "Gesture: Blow Kiss 01",                 flag = 48 },
  { dict = "anim@mp_player_intcelebrationfemale@blow_kiss",               anim = "blow_kiss",                          name = "Gesture: Blow Kiss 02",                 flag = 48 },
  { dict = "amb@world_human_cheering@male_a",                             anim = "base",                               name = "Gesture: Clap",                         flag = 49 },
  { dict = "anim@arena@celeb@flat@solo@no_props@",                        anim = "angry_clap_a_player_a",              name = "Gesture: Clap (anrgy)",                 flag = 49 },
  { dict = "anim@mp_player_intupperslow_clap",                            anim = "idle_a",                             name = "Gesture: Clap (slow)",                  flag = 49 },
  { dict = "amb@code_human_police_investigate@idle_a",                    anim = "idle_a",                             name = "Action: Police Investigate",            flag = 49 },
  { dict = "amb@code_human_police_investigate@idle_a",                    anim = "idle_b",                             name = "Action: Police Radio",                  flag = 49 },
  { dict = "melee@unarmed@streamed_variations",                           anim = "plyr_takedown_front_slap",           name = "Action: Slap",                          flag = 0 },
  { dict = "melee@unarmed@streamed_variations",                           anim = "plyr_takedown_front_headbutt",       name = "Action: Headbutt",                      flag = 0 },
  { dict = "rcmextreme2",                                                 anim = "loop_punching",                      name = "Activity: Boxing 01",                   flag = 48 },
  { dict = "anim@mp_player_intuppershadow_boxing",                        anim = "idle_a",                             name = "Activity: Boxing 02",                   flag = 49 },
  { dict = "timetable@reunited@ig_2",                                     anim = "jimmy_getknocked",                   name = "Activity: Jumping Jacks 01",            flag = 33 },
  { dict = "timetable@tracy@ig_5@base",                                   anim = "base",                               name = "Activity: Jumping Jacks 02",            flag = 33 },
  { dict = "timetable@tracy@ig_5@idle_a",                                 anim = "idle_c",                             name = "Activity: Jumping Jacks 03",            flag = 33 },
  { dict = "timetable@tracy@ig_5@idle_b",                                 anim = "idle_e",                             name = "Activity: Jumping Jacks 04",            flag = 33 },
  { dict = "timetable@tracy@ig_5@idle_b",                                 anim = "idle_d",                             name = "Activity: Jumping Jacks 05",            flag = 33 },
  { dict = "random@drunk_driver_1",                                       anim = "drunk_fall_over",                    name = "Movement: Ragdoll (drunk)",             flag = 34 },
  { dict = "move_fall",                                                   anim = "land_fall",                          name = "Movement: Ragdoll",                     flag = 34 },
  { dict = "missfinale_c2ig_11",                                          anim = "pushcar_offcliff_f",                 name = "Action: Push",                          flag = 50 },
  { dict = "amb@world_human_stupor@male@idle_a",                          anim = "idle_a",                             name = "MISC: Sit On Ground 01",                flag = 47 },
  { dict = "amb@world_human_picnic@male@idle_a",                          anim = "idle_a",                             name = "MISC: Sit On Ground 02",                flag = 47 },
  { dict = "amb@world_human_bum_slumped@male@laying_on_left_side@idle_a", anim = "idle_c",                             name = "HOBO Sleeping",                         flag = 33, sfx = "SNORING",                  sfxName = "TREVOR_NORMAL",              sfxFlg = "SPEECH_PARAMS_FORCE" },
  { dict = "amb@medic@standing@tendtodead@base",                          anim = "base",                               name = "Movement: Crouch",                      flag = 33 },
  { dict = "amb@medic@standing@kneel@base",                               anim = "base",                               name = "Movement: Kneel",                       flag = 33 },
  { dict = "mp_ped_interaction",                                          anim = "kisses_guy_a",                       name = "Action: Hug Lovingly <3",               flag = 02 },
  { dict = "amb@world_human_hang_out_street@female_arms_crossed@idle_a",  anim = "idle_a",                             name = "MISC: Cross Arms",                      flag = 49 },
  { dict = "random@street_race",                                          anim = "_car_b_lookout",                     name = "MISC: Cross Arms 02",                   flag = 49 },
  { dict = "anim@mp_player_intupperface_palm",                            anim = "idle_a",                             name = "Gesture: Facepalm (-_-)",               flag = 48 },
  { dict = "misscarsteal4@aliens",                                        anim = "rehearsal_base_idle_director",       name = "Action: Think 01",                      flag = 49 },
  { dict = "missheist_jewelleadinout",                                    anim = "jh_int_outro_loop_a",                name = "Action: Think 02",                      flag = 49 },
  { dict = "mp_suicide",                                                  anim = "pill",                               name = "Action: Commit Seppuku (×_×) (pill)",   flag = 02 },
  { dict = "mp_player_int_uppergang_sign_a",                              anim = "mp_player_int_gang_sign_a_enter",    name = "Gesture: Gang Sign 01",                 flag = 50 },
  { dict = "mp_player_int_uppergang_sign_b",                              anim = "mp_player_int_gang_sign_b_enter",    name = "Gesture: Gang Sign 02",                 flag = 50 },
  { dict = "amb@code_human_in_car_mp_actions@gang_sign_b@std@ps@base",    anim = "idle_a",                             name = "Gesture: Gang Sign 03",                 flag = 50 },
  { dict = "amb@code_human_in_car_mp_actions@gang_sign_a@bodhi@rps@base", anim = "idle_a",                             name = "Gesture: Gang Sign 04",                 flag = 50 },
  { dict = "mp_intro_seq@mcs_7_race_taunt",                               anim = "mcs_7_taunt_male",                   name = "Car: Race Taunt 01 (in-car)",           flag = 32 },
  { dict = "mp_intro_seq@mcs_7_race_taunt",                               anim = "mcs_7_taunt_female",                 name = "Car: Race Taunt 02 (in-car)",           flag = 32 },
  { dict = "missarmenian1driving_taunts@lamar_1",                         anim = "skoolinyoass",                       name = "Car: Race Taunt 03 (in-car)",           flag = 32 },
  { dict = "missarmenian1driving_taunts@lamar_1",                         anim = "keeppoping",                         name = "Car: Race Taunt 04 (in-car)",           flag = 32 },
  { dict = "missarmenian1driving_taunts@lamar_1",                         anim = "cmonmynigga",                        name = "Car: Race Taunt 05 (in-car)",           flag = 32 },
  { dict = "missarmenian1driving_taunts@franklin",                        anim = "ohyougotenginetrouble",              name = "Car: Race Taunt 05 (in-car/roofless)",  flag = 32 },
  { dict = "random@street_race",                                          anim = "grid_girl_race_start",               name = "Car: Street Racing Countdown",          flag = 32 },
  { dict = "anim@amb@carmeet@checkout_car@",                              anim = "male_d_idle_d",                      name = "Car: Checkout Car",                     flag = 32 },
  { dict = "missheat",                                                    anim = "guard_dead_ps",                      name = "Car: Dead 01 (in-car)",                 flag = 18 },
  { dict = "missmic3leadinout_mcs1",                                      anim = "cockpit_pilot",                      name = "Car: Dead 02 (in-car)",                 flag = 18 },
  { dict = "anim@amb@carmeet@checkout_car@",                              anim = "male_h_base",                        name = "MISC: Arms On Sides",                   flag = 49 },
  { dict = "anim@amb@carmeet@checkout_car@",                              anim = "male_f_idle_b",                      name = "MISC: Arms Front",                      flag = 49 },
  { dict = "anim@amb@casino@valet_scenario@pose_d@",                      anim = "base_a_m_y_vinewood_01",             name = "MISC: Arms Back",                       flag = 49 },
  { dict = "random@hitch_lift",                                           anim = "idle_f",                             name = "Gesture: Hitch Hike",                   flag = 49 },
  { dict = "random@robbery",                                              anim = "f_distressed_loop",                  name = "Action: Distressed",                    flag = 33 },
  { dict = "random@robbery",                                              anim = "f_cower_02",                         name = "Action: Cower 01",                      flag = 33 },
  { dict = "amb@code_human_cower@female@react_cowering",                  anim = "base_right",                         name = "Action: Cower 02",                      flag = 33 },
  { dict = "random@robbery",                                              anim = "f_cower_01",                         name = "Action: Cry",                           flag = 33, sfx = "WHIMPER",                  sfxName = "WAVELOAD_PAIN_MALE",         sfxFlg = "SPEECH_PARAMS_FORCE" },
  { dict = "anim@veh@lowrider@low@front_ds@arm@base",                     anim = "shunt_from_left",                    name = "Car: Lean Left (in-car)",               flag = 34 },
  { dict = "anim@veh@lowrider@low@front_ps@arm@base",                     anim = "lean_left_idle",                     name = "Car: Lean Right (in-car)",              flag = 34 },
  { dict = "anim@arena@celeb@podium@no_prop@",                            anim = "regal_c_1st",                        name = "Gesture: Bow Down",                     flag = 0 },
  { dict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@",           anim = "high_center",                        name = "Activity: Dance 04",                    flag = 33 },
  { dict = "missbigscore2aig_7@gunman",                                   anim = "boot_l_loop",                        name = "Action: Search Car Trunk",              flag = 33 },
  { dict = "anim@scripted@freemode@passed_out_vip_backseat_idle@male@",   anim = "passed_out_vip_backseat_idle",       name = "Car: Sleep In The Backseat (in-car)",   flag = 33, sfx = "SNORING",                  sfxName = "TREVOR_NORMAL",              sfxFlg = "SPEECH_PARAMS_FORCE" },
  { dict = "random@car_thief@victim_points",                              anim = "point_l",                            name = "Gesture: Point To The Left",            flag = 50 },
  { dict = "random@car_thief@victim_points",                              anim = "point_r",                            name = "Gesture: Point To The Right",           flag = 50 },
  { dict = "anim@amb@nightclub@mini@dance@dance_solo@jumper@",            anim = "high_center",                        name = "Activity: Dance 05",                    flag = 33 },
  { dict = "rcmfanatic1out_of_breath",                                    anim = "p_zero_tired_02",                    name = "Action: Out Of Breath 01",              flag = 49 },
  { dict = "re@construction",                                             anim = "out_of_breath",                      name = "Action: Out Of Breath 02",              flag = 0 },
  { dict = "anim@mp_player_intselfiethe_bird",                            anim = "idle_a",                             name = "Gesture: The Bird 01",                  flag = 49 },
  { dict = "anim@mp_player_intupperfinger",                               anim = "idle_a_fp",                          name = "Gesture: The Bird 02",                  flag = 49 },
  { dict = "misscommon@response",                                         anim = "screw_you",                          name = "Gesture: Up Yours!",                    flag = 48 },
  { dict = "anim@scripted@cbr3@ig1_vehicle_trunk_reaction@heeled@",       anim = "trunk_negative_reaction",            name = "Gesture: Disapprove",                   flag = 48 },
  { dict = "anim@scripted@cbr3@ig1_vehicle_trunk_reaction@heeled@",       anim = "trunk_positive_reaction",            name = "Gesture: Approve",                      flag = 48 },
  { dict = "misscommon@response",                                         anim = "bring_it_on",                        name = "Gesture: Bring It On!",                 flag = 48 },
  { dict = "gestures@m@standing@casual",                                  anim = "gesture_shrug_hard",                 name = "Gesture: Shrug",                        flag = 48 },
  { dict = "misscommon@response",                                         anim = "damn",                               name = "Gesture: Damn!",                        flag = 48 },
  { dict = "anim@mp_player_intincarsalutestd@ds@",                        anim = "idle_a",                             name = "Gesture: Salute 01",                    flag = 49 },
  { dict = "anim@mp_player_intuppersalute",                               anim = "idle_a",                             name = "Gesture: Salute 02",                    flag = 49 },
  { dict = "dead@fall",                                                   anim = "dead_fall_up",                       name = "Action: Levitate",                      flag = 33 },
  { dict = "dead@fall",                                                   anim = "dead_fall_down",                     name = "Action: Levitate Upside-Down",          flag = 33 },
  { dict = "move_crawl",                                                  anim = "onfront_fwd",                        name = "Movement: Crawl Forward",               flag = 33 },
  { dict = "amb@world_human_bum_standing@depressed@idle_a",               anim = "idle_b",                             name = "Action: Sad",                           flag = 33 },
  { dict = "amb@world_human_bum_standing@depressed@idle_a",               anim = "idle_a",                             name = "Action: Depressed",                     flag = 33 },
  { dict = "amb@world_human_stand_fire@male@idle_a",                      anim = "idle_a",                             name = "Action: Stand Around Camp Fire",        flag = 33 },
  { dict = "move_fall",                                                   anim = "land_roll",                          name = "Movement: Front Roll",                  flag = 32 },
  { dict = "anim@arena@celeb@flat@solo@no_props@",                        anim = "flip_a_player_a",                    name = "Movement: Backflip",                    flag = 33  , blendin = 2.69,                  blendout = 2.69,                        atime = 2000, autoOff = true},
}

hijackOptions = {
  { name = "Dance Mode",           dict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", anim = "high_center", },
  { name = "Perverts Everywhere!", dict = "switch@trevor@jerking_off",                         anim = "trev_jerking_off_loop", },
  { name = "Vanilla Unicorn",      dict = "mini@strip_club@private_dance@part3",               anim = "priv_dance_p3", },
  { name = "Zombie Mode",          dict = "special_ped@zombie@monologue_1@monologue_1b",       anim = "iamundead_1", },
}

ped_scenarios = {
  { scenario = "WORLD_HUMAN_STAND_MOBILE",               name = "Browse Phone" },
  { scenario = "WORLD_HUMAN_CHEERING",                   name = "Clap" },
  { scenario = "WORLD_HUMAN_CONST_DRILL",                name = "Construction: Drill" },
  { scenario = "WORLD_HUMAN_HAMMERING",                  name = "Construction: Hammer" },
  { scenario = "WORLD_HUMAN_WELDING",                    name = "Construction: Welding Torch" },
  { scenario = "PROP_HUMAN_BBQ",                         name = "Cook On BBQ" },
  { scenario = "WORLD_HUMAN_INSPECT_CROUCH",             name = "Crouch" },
  { scenario = "WORLD_HUMAN_DRINKING",                   name = "Drink Beer" },
  { scenario = "WORLD_HUMAN_DRUG_DEALER",                name = "Drug Dealer Smoking" },
  { scenario = "WORLD_HUMAN_DRUG_DEALER_HARD",           name = "Drug Dealer Tough" },
  { scenario = "PROP_HUMAN_BUM_BIN",                     name = "Dumpster Dive" },
  { scenario = "WORLD_HUMAN_GARDENER_PLANT",             name = "Field Planting" },
  { scenario = "WORLD_HUMAN_DRUG_FIELD_WORKERS_RAKE",    name = "Field Raking" },
  { scenario = "WORLD_HUMAN_DRUG_FIELD_WORKERS_WEEDING", name = "Field Weeding" },
  { scenario = "WORLD_HUMAN_MOBILE_FILM_SHOCKING",       name = "Film Shocking Event" },
  { scenario = "WORLD_HUMAN_MUSCLE_FLEX",                name = "Flex Muscles" },
  { scenario = "WORLD_HUMAN_STAND_FISHING",              name = "Go Fishing" },
  { scenario = "WORLD_HUMAN_HANG_OUT_STREET",            name = "Hangout (conversate)" },
  { scenario = "WORLD_HUMAN_STRIP_WATCH_STAND",          name = "Hangout (dance)" },
  { scenario = "WORLD_HUMAN_BUM_FREEWAY",                name = "HOBO Begging" },
  { scenario = "PROP_HUMAN_BUM_SHOPPING_CART",           name = "HOBO Leaning" },
  { scenario = "WORLD_HUMAN_BUM_SLUMPED",                name = "HOBO Sleeping" },
  { scenario = "WORLD_HUMAN_BUM_STANDING",               name = " HOBO Standing" },
  { scenario = "WORLD_HUMAN_BUM_WASH",                   name = "HOBO Washing" },
  { scenario = "WORLD_HUMAN_CLIPBOARD",                  name = "Hold Clipboard" },
  { scenario = "WORLD_HUMAN_HUMAN_STATUE",               name = "Human Statue" },
  { scenario = "WORLD_HUMAN_INSPECT_STAND",              name = "Inspect" },
  { scenario = "WORLD_HUMAN_JANITOR",                    name = "Janitor" },
  { scenario = "WORLD_HUMAN_JOG",                        name = "Jog" },
  { scenario = "PROP_HUMAN_SEAT_SUNLOUNGER",             name = "Lay On Sunlounger" },
  { scenario = "WORLD_HUMAN_GARDENER_LEAF_BLOWER",       name = "Leaf Blower" },
  { scenario = "WORLD_HUMAN_LEANING",                    name = "Lean 01" },
  { scenario = "WORLD_HUMAN_LEANING_CASINO_TERRACE",     name = "Lean 02" },
  { scenario = "WORLD_HUMAN_TOURIST_MAP",                name = "Look At Tourist Map" },
  { scenario = "WORLD_HUMAN_BINOCULARS",                 name = "Look Through Binoculars" },
  { scenario = "WORLD_HUMAN_MAID_CLEAN",                 name = "Maid" },
  { scenario = "WORLD_HUMAN_VEHICLE_MECHANIC",           name = "Mechanic" },
  { scenario = "WORLD_HUMAN_PAPARAZZI",                  name = "Paparazzi" },
  { scenario = "WORLD_HUMAN_CAR_PARK_ATTENDANT",         name = "Park Attendant" },
  { scenario = "WORLD_HUMAN_PARTYING",                   name = "Party" },
  { scenario = "PROP_HUMAN_PARKING_METER",               name = "Pay For Parking" },
  { scenario = "WORLD_HUMAN_PICNIC",                     name = "Picnic" },
  { scenario = "WORLD_HUMAN_GOLF_PLAYER",                name = "Player: Golf" },
  { scenario = "WORLD_HUMAN_TENNIS_PLAYER",              name = "Player: Tennis" },
  { scenario = "WORLD_HUMAN_COP_IDLES",                  name = "Police: Idle" },
  { scenario = "WORLD_HUMAN_DRUG_PROCESSORS_COKE",       name = "Process Cocaine" },
  { scenario = "WORLD_HUMAN_DRUG_PROCESSORS_WEED",       name = "Process Weed" },
  { scenario = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS",      name = "Prostitute: High-Class" },
  { scenario = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS",       name = "Prostitute: Low-Class" },
  { scenario = "WORLD_HUMAN_GUARD_PATROL",               name = "Security Guard (check)" },
  { scenario = "WORLD_HUMAN_GUARD_STAND",                name = "Security Guard (stand)" },
  { scenario = "WORLD_HUMAN_SECURITY_SHINE_TORCH",       name = "Security Guard (torch)" },
  { scenario = "WORLD_HUMAN_SMOKING",                    name = "Smoke Cigarette" },
  { scenario = "WORLD_HUMAN_SMOKING_POT",                name = "Smoke Weed" },
  { scenario = "PROP_HUMAN_SEAT_ARMCHAIR",               name = "Sit On Armchair" },
  { scenario = "PROP_HUMAN_SEAT_BAR",                    name = "Sit On Barstool" },
  { scenario = "PROP_HUMAN_SEAT_BENCH",                  name = "Sit On Bench" },
  { scenario = "PROP_HUMAN_SEAT_BENCH_DRINK",            name = "Sit On Bench/Drink" },
  { scenario = "PROP_HUMAN_SEAT_BENCH_DRINK_BEER",       name = "Sit On Bench/Drink Beer" },
  { scenario = "PROP_HUMAN_SEAT_BENCH_FOOD",             name = "Sit On Bench/Eat" },
  { scenario = "PROP_HUMAN_SEAT_CHAIR",                  name = "Sit On Chair" },
  { scenario = "PROP_HUMAN_SEAT_CHAIR_DRINK",            name = "Sit On Chair/Drink" },
  { scenario = "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER",       name = "Sit On Chair/Drink Beer" },
  { scenario = "PROP_HUMAN_SEAT_CHAIR_FOOD",             name = "Sit On Chair/Eat" },
  { scenario = "PROP_HUMAN_SEAT_CHAIR_UPRIGHT",          name = "Sit On Chair Upright" },
  { scenario = "PROP_HUMAN_SEAT_DECKCHAIR",              name = "Sit On Deckchair" },
  { scenario = "PROP_HUMAN_SEAT_DECKCHAIR_DRINK",        name = "Sit On Deckchair/Drink" },
  { scenario = "WORLD_HUMAN_SEAT_LEDGE",                 name = "Sit On Ledge" },
  { scenario = "WORLD_HUMAN_SEAT_LEDGE_EATING",          name = "Sit On Ledge/Eat" },
  { scenario = "WORLD_HUMAN_SEAT_STEPS",                 name = "Sit On Steps" },
  { scenario = "WORLD_HUMAN_SEAT_WALL",                  name = "Sit On Wall" },
  { scenario = "WORLD_HUMAN_SEAT_WALL_EATING",           name = "Sit On Wall/Eat" },
  { scenario = "WORLD_HUMAN_STAND_IMPATIENT",            name = "Stand Impatiently" },
  { scenario = "WORLD_HUMAN_STAND_FIRE",                 name = "Stand Near Fire" },
  { scenario = "WORLD_HUMAN_MUSICIAN",                   name = "Street Musician" },
  { scenario = "WORLD_HUMAN_SUNBATHE_BACK",              name = "Sunbathe (lay on back)" },
  { scenario = "WORLD_HUMAN_SUNBATHE",                   name = "Sunbathe (lay on stomach)" },
  { scenario = "WORLD_HUMAN_TOURIST_MOBILE",             name = "Take Photo" },
  { scenario = "PROP_HUMAN_ATM",                         name = "Use ATM" },
  { scenario = "WORLD_HUMAN_VALET",                      name = "Valet" },
  { scenario = "PROP_HUMAN_SEAT_BUS_STOP_WAIT",          name = "Wait At Bus Stop" },
  { scenario = "PROP_HUMAN_SEAT_STRIP_WATCH",            name = "Watch Stripper" },
  { scenario = "WORLD_HUMAN_WINDOW_SHOP_BROWSE",         name = "Window Shop" },
  { scenario = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS",     name = "Workout: Bench Press" },
  { scenario = "PROP_HUMAN_MUSCLE_CHIN_UPS",             name = "Workout: Chin-ups" },
  { scenario = "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS",        name = "Workout: Freeweights" },
  { scenario = "WORLD_HUMAN_PUSH_UPS",                   name = "Workout: Push-ups" },
  { scenario = "WORLD_HUMAN_SIT_UPS",                    name = "Workout: Sit-ups" },
  { scenario = "WORLD_HUMAN_YOGA",                       name = "Workout: Yoga" },
}

PED_TYPE   = {
  _PLAYER_0              = 0,
  _PLAYER_1              = 1,
  _NETWORK_PLAYER        = 2,
  _PLAYER_2              = 3,
  _CIVMALE               = 4,
  _CIVFEMALE             = 5,
  _COP                   = 6,
  _GANG_ALBANIAN         = 7,
  _GANG_BIKER_1          = 8,
  _GANG_BIKER_2          = 9,
  _GANG_ITALIAN          = 10,
  _GANG_RUSSIAN          = 11,
  _GANG_RUSSIAN_2        = 12,
  _GANG_IRISH            = 13,
  _GANG_JAMAICAN         = 14,
  _GANG_AFRICAN_AMERICAN = 15,
  _GANG_KOREAN           = 16,
  _GANG_CHINESE_JAPANESE = 17,
  _GANG_PUERTO_RICAN     = 18,
  _DEALER                = 19,
  _MEDIC                 = 20,
  _FIREMAN               = 21,
  _CRIMINAL              = 22,
  _BUM                   = 23,
  _PROSTITUTE            = 24,
  _SPECIAL               = 25,
  _MISSION               = 26,
  _SWAT                  = 27,
  _ANIMAL                = 28,
  _ARMY                  = 29,
}

npcList = {
  { group = PED_TYPE._PROSTITUTE, hash = 0x6E0FB794, name = "Hooker" },
  { group = PED_TYPE._PROSTITUTE, hash = 0x52580019, name = "Hooker 02" },
  { group = PED_TYPE._CIVFEMALE,  hash = 0x780C01BD, name = "VU Bartender" },
  { group = PED_TYPE._CIVMALE,    hash = 0x5442C66B, name = "Cult Fat Man" },
  { group = PED_TYPE._CIVMALE,    hash = 0x55446010, name = "Cult Old Man" },
  { group = PED_TYPE._CIVMALE,    hash = 0xCF0C7037, name = "DRE" },
  { group = PED_TYPE._CIVMALE,    hash = 0x69287899, name = "Vincent" },
  { group = PED_TYPE._CIVMALE,    hash = 0x65B93076, name = "Lamar" },
  { group = PED_TYPE._CIVMALE,    hash = 0xCE2CB751, name = "JEEBUS" },
  { group = PED_TYPE._CIVMALE,    hash = 0xA17EC96C, name = "Yusuf Amir" },
  { group = PED_TYPE._CIVMALE,    hash = 0x8CE6A476, name = "Yeti" },
  { group = PED_TYPE._CIVFEMALE,  hash = 0xB5CF80E4, name = "Cult Fat Woman" },
  { group = PED_TYPE._CIVFEMALE,  hash = 0x3BD99114, name = "Muscle Woman" },
  { group = PED_TYPE._CIVMALE,    hash = 0xDA116E7E, name = "Muscle Man" },
  { group = PED_TYPE._CIVFEMALE,  hash = 0x51D861F2, name = "Luchadora" },
  { group = PED_TYPE._ANIMAL,     hash = 0xCE5FF074, name = "Boar" },
  { group = PED_TYPE._ANIMAL,     hash = 0x4E8F95A2, name = "Husky" },
  { group = PED_TYPE._ANIMAL,     hash = 0x14EC17EA, name = "Chop" },
  { group = PED_TYPE._ANIMAL,     hash = 0x7E0C64AA, name = "Monkey" },
  { group = PED_TYPE._ANIMAL,     hash = 0xC2D06F53, name = "Monkey 02" },
  { group = PED_TYPE._ANIMAL,     hash = 0xB11BAB56, name = "Pig" },
  { group = PED_TYPE._ANIMAL,     hash = 0xFCFA9E1E, name = "Cow" },
  { group = PED_TYPE._ANIMAL,     hash = 0xC3B52966, name = "Rat" },
  { group = PED_TYPE._ARMY,       hash = 0xB3F3EE34, name = "Mercenary 01" },
  { group = PED_TYPE._ARMY,       hash = 0x5076A73B, name = "Mercenary 02" },
  { group = PED_TYPE._ARMY,       hash = 0x613E626C, name = "Mercenary 03" },
  { group = PED_TYPE._COP,        hash = 0x15F8700D, name = "Police (female)" },
  { group = PED_TYPE._COP,        hash = 0x5E3DA4A4, name = "Police (male)" },
  { group = PED_TYPE._COP,        hash = 0x8D8F1B10, name = "Police (SWAT)" },
  { group = PED_TYPE._CIVFEMALE,  hash = 0x7671A8F6, name = "Imani" },
  { group = PED_TYPE._CIVMALE,    hash = 0x4DA6E849, name = "Lester" },
  { group = PED_TYPE._CIVMALE,    hash = 0x9B810FA2, name = "Trevor" },
  { group = PED_TYPE._CIVMALE,    hash = 0xD7114C9,  name = "Michael" },
  { group = PED_TYPE._CIVMALE,    hash = 0x9B22DBAF, name = "Franklin" },
  { group = PED_TYPE._CIVMALE,    hash = 0x842DC2D6, name = "Jimmy" },
  { group = PED_TYPE._CIVFEMALE,  hash = 0x6D1E15F7, name = "Amanda" },
  { group = PED_TYPE._CIVMALE,    hash = 0xEC9E8F1C, name = "Hao" },
  { group = PED_TYPE._CIVMALE,    hash = 0x7461A0B0, name = "Devin Weston" },
  { group = PED_TYPE._CIVFEMALE,  hash = 0xDE352A35, name = "Tracy" },
  { group = PED_TYPE._CIVFEMALE,  hash = 0x2D145A18, name = "Agatha Baker" },
  { group = PED_TYPE._CIVMALE,    hash = 0x86BDFE26, name = "Solomun Richards" },
  { group = PED_TYPE._CIVMALE,    hash = 0x9B557274, name = "Personal Bodyguard" },
  { group = PED_TYPE._CIVMALE,    hash = 0x850446EC, name = "Lazlow" },
  { group = PED_TYPE._CIVMALE,    hash = 0xE80E9160, name = "Brucie Kibbutz" },
  { group = PED_TYPE._CIVMALE,    hash = 0x64611296, name = "Alien" },
}

lang_T       = {
  { name = 'English',               iso = 'en-US' },
  { name = 'Français',              iso = 'fr-FR' },
  { name = 'Deütsch',               iso = 'de-DE' },
  { name = 'Español',               iso = 'es-ES' },
  { name = 'Italiano',              iso = 'it-IT' },
  { name = 'Português (Brasil)',    iso = 'pt-BR' },
  { name = 'Русский (Russian)',     iso = 'ru-RU' },
  { name = 'Chinese (Traditional)', iso = 'zh-TW' },
  { name = 'Chinese (Simplified)',  iso = 'zh-CN' },
  { name = 'Japanese',              iso = 'ja-JP' },
  { name = 'Polish',                iso = 'pl-PL' },
}

WM                       = {
  _KEYDOWN     = 0x0100,
  _KEYUP       = 0x0101,
  _LBUTTONDOWN = 0x0201,
  _LBUTTONUP   = 0x0202,
  _MBUTTONDOWN = 0x0207,
  _MBUTTONUP   = 0x0208,
  _MOUSEWHEEL  = 0x020A,
  _RBUTTONDOWN = 0x0204,
  _RBUTTONUP   = 0x0205,
  _SYSKEYDOWN  = 0x0104,
  _SYSKEYUP    = 0x0105,
  _XBUTTONDOWN = 0x020B,
  _XBUTTONUP   = 0x020C,
}

VK_T                     = {
  { code = 0x08,    name = "[BACKSPACE]",            pressed = false, just_pressed = false },
  { code = 0x09,    name = "[TAB]",                  pressed = false, just_pressed = false },
  { code = 0x0C,    name = "[CLEAR]",                pressed = false, just_pressed = false },
  { code = 0x0D,    name = "[ENTER]",                pressed = false, just_pressed = false },
  { code = 0x10,    name = "[SHIFT]",                pressed = false, just_pressed = false },
  { code = 0x11,    name = "[CTRL]",                 pressed = false, just_pressed = false },
  { code = 0x12,    name = "[ALT]",                  pressed = false, just_pressed = false },
  { code = 0x13,    name = "[PAUSE]",                pressed = false, just_pressed = false },
  { code = 0x14,    name = "[CAPS LOCK]",            pressed = false, just_pressed = false },
  { code = 0x1B,    name = "[ESC]",                  pressed = false, just_pressed = false },
  { code = 0x20,    name = "[SPACEBAR]",             pressed = false, just_pressed = false },
  { code = 0x21,    name = "[PAGE UP]",              pressed = false, just_pressed = false },
  { code = 0x22,    name = "[PAGE DOWN]",            pressed = false, just_pressed = false },
  { code = 0x23,    name = "[END]",                  pressed = false, just_pressed = false },
  { code = 0x24,    name = "[HOME]",                 pressed = false, just_pressed = false },
  { code = 0x25,    name = "[LEFT ARROW]",           pressed = false, just_pressed = false },
  { code = 0x26,    name = "[UP ARROW]",             pressed = false, just_pressed = false },
  { code = 0x27,    name = "[RIGHT ARROW]",          pressed = false, just_pressed = false },
  { code = 0x28,    name = "[DOWN ARROW]",           pressed = false, just_pressed = false },
  { code = 0x29,    name = "[SELECT]",               pressed = false, just_pressed = false },
  { code = 0x2A,    name = "[PRINT]",                pressed = false, just_pressed = false },
  { code = 0x2B,    name = "[EXECUTE]",              pressed = false, just_pressed = false },
  { code = 0x2C,    name = "[PRINT SCREEN]",         pressed = false, just_pressed = false },
  { code = 0x2D,    name = "[INSERT]",               pressed = false, just_pressed = false },
  { code = 0x2E,    name = "[DEL]",                  pressed = false, just_pressed = false },
  { code = 0x2F,    name = "[HELP]",                 pressed = false, just_pressed = false },
  { code = 0x30,    name = "[0]",                    pressed = false, just_pressed = false },
  { code = 0x31,    name = "[1]",                    pressed = false, just_pressed = false },
  { code = 0x32,    name = "[2]",                    pressed = false, just_pressed = false },
  { code = 0x33,    name = "[3]",                    pressed = false, just_pressed = false },
  { code = 0x34,    name = "[4]",                    pressed = false, just_pressed = false },
  { code = 0x35,    name = "[5]",                    pressed = false, just_pressed = false },
  { code = 0x36,    name = "[6]",                    pressed = false, just_pressed = false },
  { code = 0x37,    name = "[7]",                    pressed = false, just_pressed = false },
  { code = 0x38,    name = "[8]",                    pressed = false, just_pressed = false },
  { code = 0x39,    name = "[9]",                    pressed = false, just_pressed = false },
  { code = 0x41,    name = "[A]",                    pressed = false, just_pressed = false },
  { code = 0x42,    name = "[B]",                    pressed = false, just_pressed = false },
  { code = 0x43,    name = "[C]",                    pressed = false, just_pressed = false },
  { code = 0x44,    name = "[D]",                    pressed = false, just_pressed = false },
  { code = 0x45,    name = "[E]",                    pressed = false, just_pressed = false },
  { code = 0x46,    name = "[F]",                    pressed = false, just_pressed = false },
  { code = 0x47,    name = "[G]",                    pressed = false, just_pressed = false },
  { code = 0x48,    name = "[H]",                    pressed = false, just_pressed = false },
  { code = 0x49,    name = "[I]",                    pressed = false, just_pressed = false },
  { code = 0x4A,    name = "[J]",                    pressed = false, just_pressed = false },
  { code = 0x4B,    name = "[K]",                    pressed = false, just_pressed = false },
  { code = 0x4C,    name = "[L]",                    pressed = false, just_pressed = false },
  { code = 0x4D,    name = "[M]",                    pressed = false, just_pressed = false },
  { code = 0x4E,    name = "[N]",                    pressed = false, just_pressed = false },
  { code = 0x4F,    name = "[O]",                    pressed = false, just_pressed = false },
  { code = 0x50,    name = "[P]",                    pressed = false, just_pressed = false },
  { code = 0x51,    name = "[Q]",                    pressed = false, just_pressed = false },
  { code = 0x52,    name = "[R]",                    pressed = false, just_pressed = false },
  { code = 0x53,    name = "[S]",                    pressed = false, just_pressed = false },
  { code = 0x54,    name = "[T]",                    pressed = false, just_pressed = false },
  { code = 0x55,    name = "[U]",                    pressed = false, just_pressed = false },
  { code = 0x56,    name = "[V]",                    pressed = false, just_pressed = false },
  { code = 0x57,    name = "[W]",                    pressed = false, just_pressed = false },
  { code = 0x58,    name = "[X]",                    pressed = false, just_pressed = false },
  { code = 0x59,    name = "[Y]",                    pressed = false, just_pressed = false },
  { code = 0x5A,    name = "[Z]",                    pressed = false, just_pressed = false },
  { code = 0x5B,    name = "[Left Windows]",         pressed = false, just_pressed = false },
  { code = 0x5C,    name = "[Right Windows]",        pressed = false, just_pressed = false },
  { code = 0x5D,    name = "[Apps]",                 pressed = false, just_pressed = false },
  { code = 0x5F,    name = "[Sleep]",                pressed = false, just_pressed = false },
  { code = 0x60,    name = "[Numpad 0]",             pressed = false, just_pressed = false },
  { code = 0x61,    name = "[Numpad 1]",             pressed = false, just_pressed = false },
  { code = 0x62,    name = "[Numpad 2]",             pressed = false, just_pressed = false },
  { code = 0x63,    name = "[Numpad 3]",             pressed = false, just_pressed = false },
  { code = 0x64,    name = "[Numpad 4]",             pressed = false, just_pressed = false },
  { code = 0x65,    name = "[Numpad 5]",             pressed = false, just_pressed = false },
  { code = 0x66,    name = "[Numpad 6]",             pressed = false, just_pressed = false },
  { code = 0x67,    name = "[Numpad 7]",             pressed = false, just_pressed = false },
  { code = 0x68,    name = "[Numpad 8]",             pressed = false, just_pressed = false },
  { code = 0x69,    name = "[Numpad 9]",             pressed = false, just_pressed = false },
  { code = 0x6A,    name = "[ * ]",                  pressed = false, just_pressed = false },
  { code = 0x6B,    name = "[ + ]",                  pressed = false, just_pressed = false },
  { code = 0x6C,    name = "[ . ]",                  pressed = false, just_pressed = false },
  { code = 0x6D,    name = "[ - ]",                  pressed = false, just_pressed = false },
  { code = 0x6E,    name = "[ . ]",                  pressed = false, just_pressed = false },
  { code = 0x6F,    name = "[ / ]",                  pressed = false, just_pressed = false },
  { code = 0x70,    name = "[F1]",                   pressed = false, just_pressed = false },
  { code = 0x71,    name = "[F2]",                   pressed = false, just_pressed = false },
  { code = 0x72,    name = "[F3]",                   pressed = false, just_pressed = false },
  { code = 0x73,    name = "[F4]",                   pressed = false, just_pressed = false },
  { code = 0x74,    name = "[F5]",                   pressed = false, just_pressed = false },
  { code = 0x75,    name = "[F6]",                   pressed = false, just_pressed = false },
  { code = 0x76,    name = "[F7]",                   pressed = false, just_pressed = false },
  { code = 0x77,    name = "[F8]",                   pressed = false, just_pressed = false },
  { code = 0x78,    name = "[F9]",                   pressed = false, just_pressed = false },
  { code = 0x79,    name = "[F10]",                  pressed = false, just_pressed = false },
  { code = 0x7A,    name = "[F11]",                  pressed = false, just_pressed = false },
  { code = 0x7B,    name = "[F12]",                  pressed = false, just_pressed = false },
  { code = 0x7C,    name = "[F13]",                  pressed = false, just_pressed = false },
  { code = 0x7D,    name = "[F14]",                  pressed = false, just_pressed = false },
  { code = 0x7E,    name = "[F15]",                  pressed = false, just_pressed = false },
  { code = 0x7F,    name = "[F16]",                  pressed = false, just_pressed = false },
  { code = 0x80,    name = "[F17]",                  pressed = false, just_pressed = false },
  { code = 0x81,    name = "[F18]",                  pressed = false, just_pressed = false },
  { code = 0x82,    name = "[F19]",                  pressed = false, just_pressed = false },
  { code = 0x83,    name = "[F20]",                  pressed = false, just_pressed = false },
  { code = 0x84,    name = "[F21]",                  pressed = false, just_pressed = false },
  { code = 0x85,    name = "[F22]",                  pressed = false, just_pressed = false },
  { code = 0x86,    name = "[F23]",                  pressed = false, just_pressed = false },
  { code = 0x87,    name = "[F24]",                  pressed = false, just_pressed = false },
  { code = 0x90,    name = "[NUM LOCK]",             pressed = false, just_pressed = false },
  { code = 0x91,    name = "[SCROLL LOCK]",          pressed = false, just_pressed = false },
  { code = 0xA0,    name = "[Left SHIFT]",           pressed = false, just_pressed = false },
  { code = 0xA1,    name = "[Right SHIFT]",          pressed = false, just_pressed = false },
  { code = 0xA2,    name = "[Left CONTROL]",         pressed = false, just_pressed = false },
  { code = 0xA3,    name = "[Right CONTROL]",        pressed = false, just_pressed = false },
  { code = 0xA4,    name = "[Left ALT]",             pressed = false, just_pressed = false },
  { code = 0xA5,    name = "[Right ALT]",            pressed = false, just_pressed = false },
  { code = 0xA6,    name = "[Browser Back]",         pressed = false, just_pressed = false },
  { code = 0xA7,    name = "[Browser Forward]",      pressed = false, just_pressed = false },
  { code = 0xA8,    name = "[Browser Refresh]",      pressed = false, just_pressed = false },
  { code = 0xA9,    name = "[Browser Stop]",         pressed = false, just_pressed = false },
  { code = 0xAA,    name = "[Browser Search]",       pressed = false, just_pressed = false },
  { code = 0xAB,    name = "[Browser Favorites]",    pressed = false, just_pressed = false },
  { code = 0xAC,    name = "[Browser Start / Home]", pressed = false, just_pressed = false },
  { code = 0xAD,    name = "[Volume Mute]",          pressed = false, just_pressed = false },
  { code = 0xAE,    name = "[Volume Down]",          pressed = false, just_pressed = false },
  { code = 0xAF,    name = "[Volume Up]",            pressed = false, just_pressed = false },
  { code = 0xB0,    name = "[Next Track]",           pressed = false, just_pressed = false },
  { code = 0xB1,    name = "[Previous Track]",       pressed = false, just_pressed = false },
  { code = 0xB2,    name = "[Stop Media]",           pressed = false, just_pressed = false },
  { code = 0xB3,    name = "[Play/Pause Media]",     pressed = false, just_pressed = false },
  { code = 0xB4,    name = "[Start Mail]",           pressed = false, just_pressed = false },
  { code = 0xB5,    name = "[Select Media]",         pressed = false, just_pressed = false },
  { code = 0xB6,    name = "[Start Application 1]",  pressed = false, just_pressed = false },
  { code = 0xB7,    name = "[Start Application 2]",  pressed = false, just_pressed = false },
  { code = 0xBA,    name = "[ ;: ]",                 pressed = false, just_pressed = false },
  { code = 0xBB,    name = "[ + ]",                  pressed = false, just_pressed = false },
  { code = 0xBC,    name = "[ , ]",                  pressed = false, just_pressed = false },
  { code = 0xBD,    name = "[ - ]",                  pressed = false, just_pressed = false },
  { code = 0xBE,    name = "[ . ]",                  pressed = false, just_pressed = false },
  { code = 0xBF,    name = "[ /? ]",                 pressed = false, just_pressed = false },
  { code = 0xC0,    name = "[ `~ ]",                 pressed = false, just_pressed = false },
  { code = 0xDB,    name = "[ {[ ]",                 pressed = false, just_pressed = false },
  { code = 0xDC,    name = "[ | ]",                  pressed = false, just_pressed = false },
  { code = 0xDD,    name = "[ ]} ]",                 pressed = false, just_pressed = false },
  { code = 0xDE,    name = "[ '\" ]",                pressed = false, just_pressed = false },
  { code = 0xDF,    name = "[VK_OEM_8]",             pressed = false, just_pressed = false },
  { code = 0xE2,    name = "[ < ]",                  pressed = false, just_pressed = false },
  { code = 0xF6,    name = "[Attn]",                 pressed = false, just_pressed = false },
  { code = 0xF9,    name = "[Erase EOF]",            pressed = false, just_pressed = false },
  { code = 0xFA,    name = "[Play]",                 pressed = false, just_pressed = false },
  { code = 0xFB,    name = "[Zoom]",                 pressed = false, just_pressed = false },
  { code = 0xFE,    name = "[Clear]",                pressed = false, just_pressed = false },
  { code = 0x10020, name = "[MOUSE 4]",              pressed = false, just_pressed = false },
  { code = 0x20040, name = "[MOUSE 5]",              pressed = false, just_pressed = false },
}

app_script_names_T = {
  "appArcadeBusiness",
  "appArcadeBusinessHub",
  "appAvengerOperations",
  "appBikerBusiness",
  "appBunkerBusiness",
  "appBusinessHub",
  "appFixerSecurity",
  "appHackerTruck",
  "appHackerTruck",
  "appInternet",
  "appSmuggler",
}

reserved_keys_T = {
  kb   = {
    0x01,
    0x07,
    0x0A,
    0x0B,
    0x1B,
    0x24,
    0x2C,
    0x2D,
    0x46,
    0x5B,
    0x5C,
    0x5E,
  },
  gpad = {
    23,
    24,
    25,
    71,
    75,
  },
}

cell_inputs_T            = {
  { control = 172, input = 1 },
  { control = 173, input = 2 },
  { control = 174, input = 3 },
  { control = 175, input = 4 },
  { control = 176, input = 5 },
  { control = 177, input = 5 },
  { control = 178, input = 5 },
  { control = 179, input = 5 },
  { control = 180, input = 1 },
  { control = 181, input = 2 },
}
